apiVersion: batch/v1
kind: Job
metadata:
  name: circle-migrator
  labels:
    app: circle-migrator
    layer: application
spec:
  ttlSecondsAfterFinished: 86400   # 24- hrs
  template:
    metadata:
      labels:
        app: circle-migrator
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: circle-migrator
        image: cciserver.azurecr.io/circle-migrator:0.1.532114-6a5071e0ed
        env:
        - name: FLYWAY_BASELINE_ON_MIGRATE
          value: "true"
        - name: POSTGRESQL_HOST
          value: "$POSTGRES_HOST"
        - name: POSTGRESQL_PORT
          value: "$POSTGRES_PORT"
        - name: POSTGRESQL_USERNAME
          value: "$POSTGRES_USERNAME"
        - name: POSTGRESQL_PASSWORD
          value: "$POSTGRES_PASSWORD"
        - name: DATABASE_URL
          value: "jdbc:postgresql://$(POSTGRESQL_HOST):$(POSTGRESQL_PORT)/domain?user=$(POSTGRESQL_USERNAME)&password=$(POSTGRESQL_PASSWORD)"
        resources:
          limits:
            cpu: 1000m
            memory: 100Mi
          requests:
            cpu: 2m
            memory: 10Mi
      restartPolicy: Never
