version: '2.1'
orbs:
  shellcheck: circleci/shellcheck@2.2.4
  slack: circleci/slack@4.2.1
workflows:
  server-scripts-ci:
    jobs:
      - shellcheck/check:
          context: server-slack-notifications
          external_sources: true
          dir: .
          post-steps:
            - slack-notify-on-failure

commands:
  install-slack-deps:
    steps:
      - run:
          command: apk add curl jq
          when: always
          
  slack-notify-on-failure:
    steps:
      - install-slack-deps
      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: main
